import { readdir, writeFile } from 'fs/promises';
import { join, basename, extname } from 'path';

const srcDir = './src';
const indexFile = join(srcDir, 'index.ts');

async function generateIndex() {
  try {
    const files = await readdir(srcDir);
    const exportStatements: string[] = [];

    for (const file of files) {
      const filePath = join(srcDir, file);
      const fileName = basename(file);
      const fileExt = extname(file);

      // Only include .ts, .tsx, .js, .jsx files and exclude index.ts itself
      if (
        (fileExt === '.ts' ||
          fileExt === '.tsx' ||
          fileExt === '.js' ||
          fileExt === '.jsx') &&
        fileName !== 'index.ts' &&
        fileName !== 'index.tsx' &&
        fileName !== 'index.js' &&
        fileName !== 'index.jsx' &&
        !fileName.startsWith('bun-env') && // Exclude bun-env.d.ts
        !fileName.startsWith('custom.d') // Exclude custom.d.ts
      ) {
        const moduleName = basename(file, fileExt);
        exportStatements.push(`export * from './${moduleName}';`);
      }
    }

    const content = `// This file is auto-generated by scripts/gen-index.ts\n// Do not edit this file directly.\n\n${exportStatements.join('\n')}\n`;
    await writeFile(indexFile, content);
    console.log(`Successfully generated ${indexFile}`);
  } catch (error) {
    console.error('Error generating index file:', error);
  }
}

generateIndex();
